name: Python package


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Upgrade pip and install general dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build and install the local Python package
    - name: Build and install local package
      run: |
        cd python-package
        python setup.py sdist
        pip install ./dist/employee_events-0.1.0.tar.gz
        cd ..

    # Step 5: Run tests
    - name: Run pytest
      run: |
        pytest -v
